version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-single
    command: >
      redis-server
      --appendonly yes
      --save 900 1
      --save 300 10
      --save 60 10000
      --maxmemory-policy noeviction
      --protected-mode no
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20


volumes:
  redis-data:
